"""Example: use VCD Analyzer Skills with OpenAI function calling.

Requires:
    pip install openai

Run:
    OPENAI_API_KEY=sk-... python vcd_integrations/openai/example.py path/to/sim.vcd

This file is meant to be readable as a tutorial more than as a polished
client. It deliberately shows the full request/response loop including the
follow-up call after function execution.
"""

import json
import os
import sys
from pathlib import Path

# Add repo root to path so `vcd_integrations` is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from vcd_integrations.openai.executor import execute_function_call


def main():
    try:
        from openai import OpenAI
    except ImportError:
        sys.exit("Install the OpenAI SDK first: pip install openai")

    if len(sys.argv) < 2:
        sys.exit("Usage: example.py <path/to/sim.vcd>")

    vcd_path = sys.argv[1]
    client = OpenAI()

    # Load the tool schemas generated by generate_functions.py
    functions_path = Path(__file__).parent / 'functions.json'
    with open(functions_path, 'r', encoding='utf-8') as f:
        tools = json.load(f)

    system_msg = (
        "You are a digital-design debug assistant. The user will hand you a "
        "VCD waveform file path. Use the vcd_* tools to inspect the waveform, "
        "starting with vcd_anomaly_detect to find issues, then drill down "
        "with vcd_causality or vcd_protocol_decode as needed. "
        "When you call a tool, always pass the file path the user provided."
    )
    user_msg = (
        "I have a VCD file at {!r}. Please analyze it for anomalies and tell "
        "me whether any AXI4 traffic looks broken."
    ).format(vcd_path)

    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]

    # Run a small multi-turn loop until the model stops calling tools.
    for turn in range(6):
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        msg = response.choices[0].message
        messages.append(msg.model_dump())

        if not msg.tool_calls:
            print("\nFinal answer from the model:\n")
            print(msg.content)
            return

        # Execute every tool call the model emitted in this turn.
        for tool_call in msg.tool_calls:
            name = tool_call.function.name
            args = json.loads(tool_call.function.arguments or '{}')
            print(f"\n[turn {turn}] calling {name} with {args}")
            envelope = execute_function_call(name, args)
            print(f"-> status={envelope.get('status')}, "
                  f"suggestions={envelope.get('suggestions')}")

            messages.append({
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": json.dumps(envelope),
            })

    print("Reached turn limit without a final answer.")


if __name__ == '__main__':
    main()
